### ISSUE TITLE
Locking fails in vboxfs because hard links are not possible.

### ISSUE THREAD

**Issue by ayang64** [nightlyone/lockfile#22]
See the following issue in go dep:

https://github.com/golang/dep/issues/947

Would it be reasonable to try os.SymLink() if os.Link() fails?

**Comment by nightlyone** [comment]
It is not clear to me on which errors return values I should use symbolic links instead of hard links and why this doesn't work in a docker container. 

To the best of my knowledge a docker container is a normal Linux process. So this seems more of a limitation of the underlying file system. 

Could you detail which file system is involved? 

What Docker version? 

On which operating system does your Docker setup run?

**Comment by ayang64** [comment]
HI!

We're using a pretty standard Docker configuration with, I assume, AUFS filesystem.

Please check out https://github.com/golang/dep/issues/947 -- there are a few people having this issue.  It might be helpful to use that bug report as a reference.

**Comment by nightlyone** [comment]
@ayang64 reported on the linked issue: Well, It looks like the linkat syscall get the EPERM as the following:

linkat(AT_FDCWD, "/shared/gopath/pkg/dep/sm.lock.735551337", AT_FDCWD, "/shared/gopath/pkg/dep/sm.lock", 0) = -1 EPERM (Operation not permitted)
/shared (vboxsf) is mounted by virtualbox and my host machine is the Mac osx.
It's recommended to set gopath local file system:)

**Comment by nightlyone** [comment]
tried to reproduce with a Linux machine as docker host.
```
$ docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp golang:1.9 go test -v
=== RUN   TestBasicLockUnlock
--- PASS: TestBasicLockUnlock (0.00s)
=== RUN   TestBusy
--- PASS: TestBusy (0.00s)
=== RUN   TestRogueDeletion
--- PASS: TestRogueDeletion (0.00s)
=== RUN   TestRogueDeletionDeadPid
--- PASS: TestRogueDeletionDeadPid (0.00s)
=== RUN   TestRemovesStaleLockOnDeadOwner
--- PASS: TestRemovesStaleLockOnDeadOwner (0.00s)
=== RUN   TestInvalidPidLeadToReplacedLockfileAndSuccess
--- PASS: TestInvalidPidLeadToReplacedLockfileAndSuccess (0.00s)
=== RUN   TestScanPidLine
--- PASS: TestScanPidLine (0.00s)
=== RUN   ExampleLockfile
--- PASS: ExampleLockfile (0.00s)
PASS
ok  	_/usr/src/myapp	0.005s
```
all tests work. 

So @ayang64 I really believe this is not an AUFS, but an VBOXFS issue and might be related to https://www.virtualbox.org/ticket/818 and similar. Since writing into VBOXFS has issues since many years now on different systems, I don't think I want to support this setup.

But I really appreciate your great analysis for tracking it down to a specific failing syscall and os+filesystem combination! It helped me to understand the scope of that failure.
